using System.Text;

namespace FirstOption.RevitMcp.Server;

/// <summary>Writes the pyRevit button files (script.py / script.cs) around a saved body.</summary>
public static class Wrappers
{
    public static string Button(CommandMeta meta, string body) => meta.Language switch
    {
        "csharp" => CSharp(meta, body),
        "cpython" => Python(meta, cpython: true),
        _ => Python(meta, cpython: false),
    };

    // The body stays in body.py. The button runs it with the same names the MCP bridge gives:
    // doc, uidoc, uiapp, app, args, DB, UI — inside one transaction.
    private static string Python(CommandMeta meta, bool cpython)
    {
        var sb = new StringBuilder();
        if (cpython) sb.AppendLine("#! python3");
        sb.AppendLine("# -*- coding: utf-8 -*-");
        sb.AppendLine("\"\"\"" + meta.Description.Replace("\"\"\"", "'''") + "\"\"\"");
        sb.AppendLine("# Generated by the FirstOption Revit MCP. Edit body.py, not this file.");
        sb.AppendLine("import io");
        sb.AppendLine("import os");
        sb.AppendLine("from Autodesk.Revit import DB, UI");
        sb.AppendLine();
        sb.AppendLine("uiapp = __revit__");
        sb.AppendLine("uidoc = uiapp.ActiveUIDocument");
        sb.AppendLine("doc = uidoc.Document if uidoc else None");
        sb.AppendLine("app = uiapp.Application");
        sb.AppendLine("args = {}");
        sb.AppendLine();
        sb.AppendLine("_body_path = os.path.join(os.path.dirname(__file__), 'body.py')");
        sb.AppendLine("with io.open(_body_path, encoding='utf-8') as _f:");
        sb.AppendLine("    _code = compile(_f.read(), _body_path, 'exec')");
        sb.AppendLine();
        sb.AppendLine("_tx = None");
        sb.AppendLine("if doc is not None and not doc.IsModifiable:");
        sb.AppendLine("    _tx = DB.Transaction(doc, " + PyString(meta.Title) + ")");
        sb.AppendLine("    _tx.Start()");
        sb.AppendLine("try:");
        sb.AppendLine("    exec(_code, globals())");
        sb.AppendLine("    if _tx is not None:");
        sb.AppendLine("        _tx.Commit()");
        sb.AppendLine("except Exception:");
        sb.AppendLine("    if _tx is not None and _tx.HasStarted() and not _tx.HasEnded():");
        sb.AppendLine("        _tx.RollBack()");
        sb.AppendLine("    raise");
        return sb.ToString();
    }

    private static string CSharp(CommandMeta meta, string body)
    {
        var (usings, code) = CSharpSource.SplitUsings(body);
        var cls = "Cmd_" + meta.Name;
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by the FirstOption Revit MCP. Edit body.cs, then save the command again through the MCP.");
        sb.AppendLine("// " + meta.Description.Replace("\n", " "));
        foreach (var u in CSharpSource.DefaultUsings.Concat(usings).Distinct()) sb.AppendLine(u);
        sb.AppendLine("using Autodesk.Revit.Attributes;");
        sb.AppendLine();
        sb.AppendLine("namespace FirstOptionLibrary");
        sb.AppendLine("{");
        sb.AppendLine("    public static class " + cls + "_Script");
        sb.AppendLine("    {");
        sb.AppendLine("        public static object Run(UIApplication uiapp, UIDocument uidoc, Document doc, Autodesk.Revit.ApplicationServices.Application app, IDictionary<string, object> args, System.IO.TextWriter Console)");
        sb.AppendLine("        {");
        sb.AppendLine(code);
        sb.AppendLine("            return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [Transaction(TransactionMode.Manual)]");
        sb.AppendLine("    public class " + cls + " : IExternalCommand");
        sb.AppendLine("    {");
        sb.AppendLine("        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)");
        sb.AppendLine("        {");
        sb.AppendLine("            var uiapp = commandData.Application;");
        sb.AppendLine("            var uidoc = uiapp.ActiveUIDocument;");
        sb.AppendLine("            var doc = uidoc != null ? uidoc.Document : null;");
        sb.AppendLine("            var output = new System.IO.StringWriter();");
        sb.AppendLine("            Transaction tx = null;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                if (doc != null && !doc.IsModifiable) { tx = new Transaction(doc, \"" + meta.Title.Replace("\"", "'") + "\"); tx.Start(); }");
        sb.AppendLine("                var result = " + cls + "_Script.Run(uiapp, uidoc, doc, uiapp.Application, new Dictionary<string, object>(), output);");
        sb.AppendLine("                if (tx != null) tx.Commit();");
        sb.AppendLine("                var text = output.ToString();");
        sb.AppendLine("                if (result != null) text += (text.Length > 0 ? \"\\n\" : \"\") + result;");
        sb.AppendLine("                if (text.Length > 0) TaskDialog.Show(\"" + meta.Title.Replace("\"", "'") + "\", text);");
        sb.AppendLine("                return Result.Succeeded;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (tx != null && tx.HasStarted() && !tx.HasEnded()) tx.RollBack();");
        sb.AppendLine("                message = ex.Message;");
        sb.AppendLine("                return Result.Failed;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string PyString(string s) => "u'" + (s ?? "").Replace("\\", "\\\\").Replace("'", "\\'") + "'";
}

/// <summary>Same "body" convention as the C# runner in the Revit add-in.</summary>
public static class CSharpSource
{
    public static readonly string[] DefaultUsings =
    {
        "using System;",
        "using System.Collections.Generic;",
        "using System.Linq;",
        "using System.Text;",
        "using Autodesk.Revit.DB;",
        "using Autodesk.Revit.UI;",
        "using Autodesk.Revit.UI.Selection;",
    };

    public static (List<string> Usings, string Body) SplitUsings(string code)
    {
        var usings = new List<string>();
        var lines = (code ?? "").Replace("\r\n", "\n").Split('\n');
        var i = 0;
        for (; i < lines.Length; i++)
        {
            var t = lines[i].Trim();
            if (t.Length == 0 || t.StartsWith("//")) continue;
            if (t.StartsWith("using ") && t.EndsWith(";") && !t.Contains("(")) { usings.Add(t); continue; }
            break;
        }
        return (usings, string.Join("\n", lines.Skip(i)));
    }
}
